from .redirect_from_login import redirect_from_login
from .researcher_home import researcher_view
from .researcher_settings_page import researcher_settings_view, ResearcherDeleteView
from .researcher_user_page import researcher_user_view
from .researcher_registration import researcher_registration
from .studentuser_page import student_user_view
from .student_settings_page import student_settings_view
from .student_home import student_view
from .student_management import student_management
from .student_registration import student_registration
from .view_response import view_response, update_overall_response_feedback, update_node_response_feedback
from .logout import logout
