# Generated by Django 3.1.3 on 2020-12-15 01:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTemplate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, default=0)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=4000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=4000)),
                ('video_url', models.CharField(max_length=100)),
                ('terminal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateNodeChoice',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('choice_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateResponse',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_response', to='conversation_templates.conversationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateNodeResponse',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('transcription', models.CharField(max_length=1000)),
                ('position_in_sequence', models.IntegerField()),
                ('template_node', models.ManyToManyField(related_name='template_node_responses', to='conversation_templates.TemplateNode')),
            ],
        ),
        migrations.AddField(
            model_name='templatenode',
            name='choices',
            field=models.ManyToManyField(related_name='template_node', to='conversation_templates.TemplateNodeChoice'),
        ),
        migrations.AddField(
            model_name='conversationtemplate',
            name='nodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_contains', to='conversation_templates.templatenode'),
        ),
        migrations.AddField(
            model_name='conversationtemplate',
            name='start_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_starts', to='conversation_templates.templatenode'),
        ),
    ]
