# Generated by Django 3.1.3 on 2021-01-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('conversation_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateresponse',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='template_responses', to='users.assignment'),
        ),
        migrations.AddField(
            model_name='templateresponse',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='template_responses', to='users.student'),
        ),
        migrations.AddField(
            model_name='templateresponse',
            name='template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='template_responses', to='conversation_templates.conversationtemplate'),
        ),
        migrations.AddField(
            model_name='templatenoderesponse',
            name='parent_template_response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='node_responses', to='conversation_templates.templateresponse'),
        ),
        migrations.AddField(
            model_name='templatenoderesponse',
            name='template_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='conversation_templates.templatenode'),
        ),
        migrations.AddField(
            model_name='templatenodechoice',
            name='destination_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_choices', to='conversation_templates.templatenode'),
        ),
        migrations.AddField(
            model_name='templatenodechoice',
            name='parent_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to='conversation_templates.templatenode'),
        ),
        migrations.AddField(
            model_name='templatenode',
            name='parent_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='template_nodes', to='conversation_templates.conversationtemplate'),
        ),
        migrations.AddField(
            model_name='conversationtemplate',
            name='researcher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.researcher'),
        ),
    ]
