# Generated by Django 3.1.3 on 2020-12-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationtemplate',
            name='start_node',
        ),
        migrations.AddField(
            model_name='templatenode',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatenodechoice',
            name='node_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='template_node_choice', to='conversation_templates.templatenode'),
        ),
        migrations.AlterField(
            model_name='conversationtemplate',
            name='nodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_template', to='conversation_templates.templatenode'),
        ),
    ]
