# Generated by Django 3.1.3 on 2021-01-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0002_auto_20210107_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefolder',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
