# Generated by Django 3.1.3 on 2021-01-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0003_auto_20210103_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateresponse',
            name='completion_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
