# Generated by Django 3.1.3 on 2021-01-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0003_auto_20210110_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefolder',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
