# Generated by Django 3.1.3 on 2020-12-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0004_templatefolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefolder',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='folder', to='conversation_templates.ConversationTemplate'),
        ),
    ]
