# Generated by Django 3.1.3 on 2021-01-13 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('conversation_templates', '0004_auto_20210112_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefolder',
            name='researcher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='template_folder', to='users.researcher'),
        ),
        migrations.AlterUniqueTogether(
            name='templatefolder',
            unique_together={('name', 'researcher')},
        ),
    ]
