# Generated by Django 3.1.3 on 2021-01-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0004_auto_20210112_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatenoderesponse',
            name='selected_choice',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_response', to='conversation_templates.templatenodechoice'),
        ),
    ]
