# Generated by Django 3.1.3 on 2021-01-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0005_templatenoderesponse_selected_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatenoderesponse',
            name='selected_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_response', to='conversation_templates.templatenodechoice'),
        ),
    ]
