# Generated by Django 3.1.3 on 2021-01-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0005_auto_20210112_2242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatefolder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='templatefolder',
            name='researcher',
        ),
    ]
