# Generated by Django 3.1.3 on 2020-12-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0006_auto_20201230_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefolder',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='folder', to='conversation_templates.ConversationTemplate'),
        ),
    ]
