# Generated by Django 3.1.3 on 2020-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject_labels',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='users.SubjectLabel'),
        ),
    ]
