# Generated by Django 3.1.3 on 2020-12-20 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_templates', '0003_auto_20201219_1846'),
        ('users', '0004_auto_20201214_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='labels',
            new_name='subject_labels',
        ),
        migrations.RenameField(
            model_name='subjectlabel',
            old_name='file_name',
            new_name='label_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='students',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='student',
            name='available_templates',
        ),
        migrations.RemoveField(
            model_name='student',
            name='completed_templates',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='template_response',
        ),
        migrations.AddField(
            model_name='assignment',
            name='conversation_templates',
            field=models.ManyToManyField(related_name='assignments', to='conversation_templates.ConversationTemplate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='researcher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.researcher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to='users.researcher'),
        ),
        migrations.AddField(
            model_name='subjectlabel',
            name='researcher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='users.researcher'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectlabel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectlabel',
            name='students',
            field=models.ManyToManyField(related_name='labels', to='users.Student'),
        ),
    ]
